# -*- coding: utf-8 -*-
"""Email_Spam_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fc6UNA5Ax7g5RpYA6JY_8u7xwh83BOwi

#1. Environment Setup and Dataset Upload
"""

#Upload dataset
from google.colab import files
uploaded = files.upload()

#Unzip the Dataset
import zipfile

with zipfile.ZipFile('archive.zip', 'r') as zip_ref:
    zip_ref.extractall('dataset')

#Check what files are inside
import os

os.listdir('dataset')

#Load the CSV file
import pandas as pd

df = pd.read_csv('dataset/emails.csv', encoding='latin-1')
df.head()

"""#2. Data Exploration and Visualization"""

#Check the dataset columns
df.columns

#Check Dataset Information
df.info()

#check missing values
df.isnull().sum()

"""Check Spam vs Ham Distribution"""

df['spam'].value_counts()

import matplotlib.pyplot as plt

df['spam'].value_counts().plot(kind='bar')

plt.title("Spam vs Non-Spam Emails")
plt.xticks([0,1],["Not Spam","Spam"], rotation=0)
plt.ylabel("Number of Emails")

plt.show()

"""#3. Text Preprocessing"""

#Install NLP Stopwords
import nltk
nltk.download('stopwords')

# Text Cleaning (Preprocessing)

import re
import string
from nltk.corpus import stopwords

# load stopwords
stop_words = set(stopwords.words('english'))

# function to clean email text
def clean_text(text):

    # convert text to lowercase
    text = text.lower()

    # remove numbers
    text = re.sub(r'\d+', '', text)

    # remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # split into words
    words = text.split()

    # remove stopwords
    words = [word for word in words if word not in stop_words]

    return " ".join(words)

#Apply Cleaning to Dataset

df['clean_text'] = df['text'].apply(clean_text)

# view updated dataset
df.head()

"""#4. Feature Extraction"""

# Define Features and Labels

# X = input data (email text)
X = df['clean_text']

# y = target variable (spam or not spam)
y = df['spam']

# Convert Text to Numerical Features using TF-IDF

from sklearn.feature_extraction.text import TfidfVectorizer

# create vectorizer
vectorizer = TfidfVectorizer(max_features=5000)

# transform text into numerical matrix
X_tfidf = vectorizer.fit_transform(X)

#Train-Test Split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf,
    y,
    test_size=0.2,
    random_state=42
)

"""#5. Model Training"""

from sklearn.naive_bayes import MultinomialNB

# create model
model = MultinomialNB()

# train model
model.fit(X_train, y_train)

#prediction
y_pred = model.predict(X_test)

"""#6. Model Evaluation"""

# Model Evaluation Metrics

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))

"""#7. Results Visualization"""

# Confusion Matrix

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Not Spam", "Spam"]
)

disp.plot()

plt.title("Confusion Matrix")

plt.show()

"""#8. Spam Prediction"""

# Custom Email Prediction Function

def predict_email(email):

    cleaned = clean_text(email)

    vector = vectorizer.transform([cleaned])

    prediction = model.predict(vector)[0]

    if prediction == 1:
        return "Spam"
    else:
        return "Not Spam"

predict_email("Congratulations you won a free lottery ticket claim now")

predict_email("Hi team please review the attached meeting report")

predict_email("Reset your password")

predict_email("Limited offer investment opportunity guaranteed profit")

predict_email("Cheap viagra buy now limited offer")

predict_email("Congratulations you won a free iPhone click here now")

"""Although the classifier achieves high accuracy (97.8%), some spam messages may still be misclassified as non-spam. This occurs because the model relies on patterns learned from the training dataset and may not recognize new or uncommon spam phrases. More advanced models such as deep learning or contextual language models could further improve detection performanc"""

# Training and Testing Accuracy

train_accuracy = model.score(X_train, y_train)
test_accuracy = model.score(X_test, y_test)

print("Training Accuracy:", train_accuracy)
print("Testing Accuracy:", test_accuracy)

# Training vs Testing Accuracy Plot

import matplotlib.pyplot as plt

labels = ["Training Accuracy", "Testing Accuracy"]
values = [train_accuracy, test_accuracy]

plt.figure(figsize=(6,4))
plt.bar(labels, values, color=["blue","orange"])

plt.ylim(0.9,1.0)
plt.ylabel("Accuracy")
plt.title("Training vs Testing Accuracy")

for i, v in enumerate(values):
    plt.text(i, v + 0.002, f"{v:.3f}", ha='center')

plt.show()

"""#9. Model & Visualas Saving"""

# STEP 22 — Save Model

import pickle

pickle.dump(model, open("spam_model.pkl","wb"))
pickle.dump(vectorizer, open("vectorizer.pkl","wb"))

from google.colab import files

files.download("spam_model.pkl")
files.download("vectorizer.pkl")

# Save spam distribution chart

df['spam'].value_counts().plot(kind='bar')
plt.title("Spam vs Non-Spam Emails")
plt.xticks([0,1], ["Not Spam", "Spam"], rotation=0)
plt.ylabel("Number of Emails")
plt.savefig("spam_distribution.png")
plt.show()

# Save confusion matrix

disp.plot()
plt.title("Confusion Matrix")
plt.savefig("confusion_matrix.png")
plt.show()

from google.colab import files

files.download("spam_distribution.png")
files.download("confusion_matrix.png")

plt.savefig("training_testing_accuracy.png")

from google.colab import files
files.download("training_testing_accuracy.png")